gfx/env/3dm747bk.tga
gfx/env/3dm747dn.tga
gfx/env/3dm747ft.tga
gfx/env/3dm747lf.tga
gfx/env/3dm747rt.tga
gfx/env/3dm747up.tga
models/ze_portal_test/Atlas_en_apuros_v2.mdl
models/ze_portal_test/Idle_Eggbot_v2.mdl
models/ze_portal_test/Portal_gun_v2.mdl
sound/ze_portal_test/activando.wav
sound/ze_portal_test/Bienvenido_v2.wav
sound/ze_portal_test/biggun2.wav
sound/ze_portal_test/Escape_v2.wav
sound/ze_portal_test/Excelente.wav
sound/ze_portal_test/Hola.wav
sound/ze_portal_test/mh_mh.wav
sound/ze_portal_test/objetivo_perdido.wav
sound/ze_portal_test/Puerta_que_falla_v5.wav
sound/ze_portal_test/Trampa_v2.wav
sprites/laserbeam.spr
sprites/muzzleflash2.spr
