models/rhyzome/grass5.mdl
models/rhyzome/robotson02_small.mdl
models/rhyzome/saw_b.mdl
models/rhyzome/saw_s.mdl
models/rhyzome/stone_all_1_mdl.mdl
models/rhyzome/temple_tree01.mdl
models/rhyzome/w2.mdl
models/rhyzome/w4.mdl
models/rhyzome/tracker.mdl
models/rhyzome/ze_tank02.mdl
models/rhyzome/ze1_biglog01.mdl
models/rhyzome/ze1_woods01.mdl
models/rhyzome/ze1_woods04.mdl
models/rhyzome/ze1_woods18.mdl
models/rhyzome/ze1_woods19.mdl

sound/rhyzome/bridge_creak.wav
sound/rhyzome/cave_amb.wav
sound/rhyzome/forest_amb1.wav
sound/rhyzome/call_your_death.wav
sound/rhyzome/saw_amb.wav
sound/rhyzome/saw_rotating.wav
sound/rhyzome/tunnel_amb.wav
sound/rhyzome/water_crashing.wav
sound/rhyzome/water_wheel.wav
sound/rhyzome/waterfall_amb.wav
sound/rhyzome/waterflow_cave_inside.wav
sound/rhyzome/waterflow_cave_outside.wav
sound/rhyzome/wind_amb.wav

gfx/env/camobk.tga
gfx/env/camodn.tga
gfx/env/camoft.tga
gfx/env/camolf.tga
gfx/env/camort.tga
gfx/env/camoup.tga

overviews/ze_rhyzome.bmp
overviews/ze_rhyzome.txt